cc_library(
    name = "hello-time",
    srcs = ["hello-time.cc"],
    hdrs = ["hello-time.h"],
    visibility = ["//main:__pkg__"],
)

cc_library(
    name = "hello-opencv",
    srcs = ["hello-opencv.cc"],
    hdrs = ["hello-opencv.h"],
    visibility = ["//main:__pkg__"],
)

cc_library(
    name = "hello-pcl",
    srcs = ["pcl.cpp"],
    hdrs = ["pcl.h"],
    visibility = ["//main:__pkg__"],
)
